version: "3"


services:
    redis:
        image: redis:latest
        restart: always
        ports:
        - 6379:${REDIS_PORT}
        environment:
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - REDIS_PORT=${REDIS_PORT}
        - REDIS_DATABASES=16
        env_file: .env

    bot:
        build: .
        depends_on:
            - redis
        env_file: .env


